server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://git-ssh.unosquare.com/java-coe/microservices/sergio-gomez-microservices-app/configurationserver.git
          passphrase: lorna
          ignoreLocalSshSettings: true
          hostKey: AAAAB3NzaC1yc2EAAAADAQABAAABAQCwua5E+W4Oh+gMkAwOyIpJoVvLN4ri4SceDolhyIpUDnuC4C4GwY6mjm3cQCsJTyS2AADszLCQaRVuPM9gjWR4lam0FSRYEYolE1P3D53Ws0wNYUXwV+MoR1JEpUJDQLzcW3rHzKRcFzvQ5dFZJbpw4enlt5cei6Md4ILBNmv7Osst8AACgV7btl0tQwqTJyZFCcpmHdBzX6TndClBTQJV/uG/xw1TefmRPgAH1m2HxCNVZYyvb80Mwt42SLR70y9EejEPa010yjz0XI6it4DI5sv2JQMt5bLgKf+6nqH8nYIdi/PY55wj07a/XW1pho9sLueWyyS6Rw20sjKgrqu5
          hostKeyAlgorithm: ssh-rsa
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            Proc-Type: 4,ENCRYPTED
            DEK-Info: DES-EDE3-CBC,0B83B4F7AF765A8E

            mcDUCA7G91s1O28IpxYP5BBIH1cMmYGKBNBfivGpEnCaxhRRtOXr7cMkZBNK0BoH
            7ihBEFzuqgGWRP+WGqlK92BFyIvIWcG/HYAtPCBkhPvzayK6VbY2InsjXwLbdHTP
            c4SG60QI3ZX4s0eE+U6rbunNGUsmUkp/ZVAjaQunNkEnfcQsuwPku/n3RVeamjuD
            HzCX31YqBEdNydCHzjS08cH2tcXOhZLMyE/AlgRRiyb4m5PEep7bwGTD58tj+Nxx
            FjQQAfEKUTC51NRl+BxkCiBZ47l1x6wI4tR09c8JN3yiqL+StaeD8izh/hbxZUUv
            nJPMnZxC8Q5ejzaAi5Yj/v/DnviQ9n3AmFMqKhRDyPbaGukxwEtQMCMKLmVi6Ch8
            lXQs8MRwnTEpzHyPWZDxyz7YkYe3ixRizGxgeQbk0UZBtDPwKq6nBLSbybOsx/R+
            tZNEAkaIhTyktXPkJK6PIFAIQpOYGxdn++qYSxjzSqC5cvfkbCz38zitKN3u+wTC
            DjPJic9NK+RP4oCrFU7NzPD2rE4Y3SU+y4CqrFJpTvxfOtfD4XkXu7UWOHSyToFA
            GkWxZBJM6ODp4LdzucMDXmkpNSeuoPHq6m+CULKLB8Udn+w2J8N4UCbSLmTWyiAD
            eOhKpqLlyBgS5kwcjI0LPkki2cjBp69OrC5D6gs1TSbvPjNKa6f6l/BabWLbIH3S
            LvOo6Y0KzH7tMkkk5A1Lcq7Xm/D3PYLcWVR/eK8qFmNMksxMngUNPN1NbuxMvfhh
            bLhSr7ccIvO7GctNQ/0CzVFJxA3PtUuulGIlLu4AJ35zOaF4+Cr7DOyTztUxPVrD
            HtA4k8PCpxGoLw6868K1x2m1MkwmAgl8KTv+cZBvzuwLg+fDimcT9ELiFekVsMwX
            fPrq7Tk6CmjTRWRPNlKwyajxCEmbuYqhZsbM2drTA5yCTDboHmLflzFTZkZRWKA8
            TsODAF6NzVKs9aDs1ScWzGfWChvxxjQgc550ryJwTZD8DycpYtn+wDwXJFdZK1kb
            6CzEXV0X5qNR5aUfnY3aQZ/Q2QmwiBq/OWu53PzXM8T9sOcQTXRspLlR79x6VqXn
            3q3uE0mkNK2Dt13AjDmM1X3AR1olS5Cy6f2LdOoacFKZQBpAvnadNsdYvpj0Pk7W
            D9/sqh2+m+JRhyNs4hUcVI+E6ffLexNQzN5wOkLehvvqBQwxjyc4f+szqsuNm/rw
            OlskKft20u7ZDclxY5DGLiiMAtuRxqCNzdcZ1K8/ZGlpGYNE8ecyde+anetFHxQx
            Nf7WcjkfclCDSnHSWHNqnVOvGzDkBUfd6hrYcG+H6NvrM1+zKI1ps1WZXOLXHtml
            IAWRXw4UqYu2sEmSngnC+hPodpxDpcoxLmqp9O8zmN7QM7UXboyaMS0NNgJoIAwR
            QOgUUuyHj7k3t/6rHkjl8CSU8L3517FKkWLZLHTDl0n78VuEEjhMdIrtZrvgq0Mv
            dwHcjzzNE3K85cXZgE6XWiAxxqbYBYnx+eoPhpHzl53+ATiWXWHIN0WdhZJv3wkw
            vKfe6tK5e8ozAFhe0HL1Vy2wP9TAF7BVXhrc4HE2F5RHbqbaSkfMUA==
            -----END RSA PRIVATE KEY-----